# Generated by Django 4.0.2 on 2022-02-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='class_title',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='news',
            name='class_title',
        ),
    ]
