# Generated by Django 4.0.2 on 2022-02-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_rename_class_title_exercise_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='add_student_national_code',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
