# Generated by Django 4.0.2 on 2022-02-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_lesson_add_student_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.lesson'),
        ),
    ]
