# Generated by Django 4.0.2 on 2022-02-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_exercise_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerexercise',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
